S2_AUTHOR_CANDIDATES = {
    "Eric R. Larson": [
        {
            "id": "39673101",
            "share": 60.4,
            "first_year": 2008,
            "last_year": 2022,
            "publications": [
                {"year": 2022, "title": "Overlooked invaders? Ecological impacts of non‐game, native transplant fishes in the United States"},
                {"year": 2021, "title": "Diversity Metrics Are Robust to Differences in Sampling Location and Depth for Environmental DNA of Plants in Small Temperate Lakes"},
                {"year": 2021, "title": "High stream flows dilute environmental DNA (eDNA) concentrations and reduce detectability"},
                {"year": 2020, "title": "Field storage of water samples affects measured environmental DNA concentration and detection"},
                {"year": 2020, "title": "From eDNA to citizen science: emerging tools for the early detection of invasive species"},
                {"year": 2020, "title": "No evidence that crayfish carcasses produce detectable environmental DNA (eDNA) in a stream enclosure experiment"},
                {"year": 2019, "title": "Do roads or streams explain plant invasions in forested protected areas?"},
                {"year": 2019, "title": "Does invasive species research use more militaristic language than other ecology and conservation biology literature?"},
                {"year": 2019, "title": "Effects of forest windstorm disturbance on invasive plants in protected areas of southern Illinois, USA"},
                {"year": 2019, "title": "Habitat explains patterns of population decline for an invasive crayfish."},
                {"year": 2019, "title": "Radiotelemetry reveals effects of upstream biomass and UV exposure on environmental DNA occupancy and detection for a large freshwater turtle"},
                {"year": 2019, "title": "Towards a cohesive strategy for the conservation of the United States’ diverse and highly endemic crayfish fauna"},
                {"year": 2018, "title": "Development and field validation of an environmental DNA (eDNA) assay for invasive clams of the genus Corbicula"},
                {"year": 2018, "title": "Distribution, habitat associations, and conservation status updates for the pilose crayfish Pacifastacus gambelii (Girard, 1852) and Snake River pilose crayfish Pacifastacus connectens (Faxon, 1914) of the western United States"},
                {"year": 2018, "title": "Environmental DNA (eDNA) applications for the conservation of imperiled crayfish (Decapoda: Astacidea) through monitoring of invasive species barriers and relocated populations"},
                {"year": 2018, "title": "Environmental DNA detects a rare large river crayfish but with little relation to local abundance"},
                {"year": 2018, "title": "Is conservation right to go big? Protected area size and conservation return-on-investment"},
                {"year": 2018, "title": "Predicting the potential distribution of the non-native Red Swamp Crayfish Procambarus clarkii in the Laurentian Great Lakes"},
                {"year": 2017, "title": "Environmental DNA (eDNA) detects the invasive crayfishes Orconectes rusticus and Pacifastacus leniusculus in large lakes of North America"},
                {"year": 2017, "title": "Factoring economic costs into conservation planning may not improve agreement over priorities for protection"},
                {"year": 2017, "title": "Invasive dreissenid mussels benefit invasive crayfish but not native crayfish in the Laurentian Great Lakes"},
                {"year": 2016, "title": "Comparison of trophic function between the globally invasive crayfishes Pacifastacus leniusculus and Procambarus clarkii"},
                {"year": 2016, "title": "Environmental DNA (eDNA) Detection Probability Is Influenced by Seasonal Activity of Organisms"},
                {"year": 2016, "title": "Environmental DNA (eDNA) detects the invasive rusty crayfish Orconectes rusticus at low abundances"},
                {"year": 2016, "title": "Phylogenetic species delimitation for crayfishes of the genus Pacifastacus"},
                {"year": 2016, "title": "Phylogeographic insights into the invasion history and secondary spread of the signal crayfish in Japan"},
                {"year": 2016, "title": "Risk Analysis and Bioeconomics of Invasive Species to Inform Policy and Management"},
                {"year": 2015, "title": "Are conservation organizations configured for effective adaptation to global change"},
                {"year": 2015, "title": "Comparison of 13C and 15N discrimination factors and turnover rates between congeneric crayfish Orconectes rusticus and O. virilis (Decapoda, Cambaridae)"},
                {"year": 2015, "title": "Constraints of philanthropy on determining the distribution of biodiversity conservation funding"},
                {"year": 2015, "title": "Do invasive rusty crayfish (Orconectes rusticus) decouple littoral and pelagic energy flows in lake food webs?"},
                {"year": 2015, "title": "Historical Biogeography of Pacifastacus Crayfishes and their Branchiobdellidan and Entocytherid Ectosymbionts in Western North America"},
                {"year": 2014, "title": "A lack of response of the financial behaviors of biodiversity conservation nonprofits to changing economic conditions"},
                {"year": 2014, "title": "Generalized “avatar” niche shifts improve distribution models for invasive species"},
                {"year": 2014, "title": "Protected area acquisition costs show economies of scale with area"},
                {"year": 2013, "title": "A global meta-analysis of the ecological impacts of nonnative crayfish"},
                {"year": 2013, "title": "An assessment of life-history studies for USA and Canadian crayfishes: identifying biases and knowledge gaps to improve conservation and management"},
                {"year": 2013, "title": "Crayfish occupancy and abundance in lakes of the Pacific Northwest, USA"},
                {"year": 2013, "title": "Effects of Climate Change, Invasive Species, and Disease on the Distribution of Native European Crayfishes"},
                {"year": 2012, "title": "The signal crayfish is not a single species: cryptic diversity and invasions in the Pacific Northwest range of Pacifastacus leniusculus"},
                {"year": 2012, "title": "Using avatar species to model the potential distribution of emerging invaders"},
                {"year": 2011, "title": "Habitat structure determines resource use by zooplankton in temperate lakes."},
                {"year": 2011, "title": "Life-History Notes on Cambarus hubbsi Creaser (Hubbs Crayfish) from the South Fork Spring River, Arkansas"},
                {"year": 2011, "title": "National parks as protected areas for U.S. freshwater fish diversity"},
                {"year": 2011, "title": "Shoreline urbanization interrupts allochthonous subsidies to a benthic consumer over a gradient of lake size"},
                {"year": 2011, "title": "Systematic Conservation Planning in the Face of Climate Change: Bet-Hedging on the Columbia Plateau"},
                {"year": 2011, "title": "The State of Crayfish in the Pacific Northwest"},
                {"year": 2010, "title": "Decoupled conservatism of Grinnellian and Eltonian niches in an invasive arthropod"},
                {"year": 2010, "title": "Latent Extinction and Invasion Risk of Crayfishes in the Southeastern United States"},
                {"year": 2009, "title": "Disturbance and species displacement: different tolerances to stream drying and desiccation in a native and an invasive crayfish"},
                {"year": 2009, "title": "First record of Orconectes rusticus (Girard, 1852) (Decapoda, Cambaridae) west of the Great Continental Divide in North America"},
                {"year": 2009, "title": "Home-field advantage: native signal crayfish (Pacifastacus leniusculus) out consume newly introduced crayfishes for invasive Chinese mystery snail (Bellamya chinensis)"},
                {"year": 2009, "title": "Widespread Distribution of the Non-Native Northern Crayfish (Orconectes virilis) in the Columbia River Basin"},
                {"year": 2008, "title": "Comparative Life History of Native (Orconectes Eupunctus) and Introduced (Orconectes Neglectus) Crayfishes in The Spring River Drainage of Arkansas and Missouri"},
                {"year": 2008, "title": "Do schools and golf courses represent emerging pathways for crayfish invasions"},
                {"year": 2008, "title": "Does juvenile competition explain displacement of a native crayfish by an introduced crayfish?"},
                {"year": 2008, "title": "Efficiency of a Quadrat Sampling Technique for Estimating Riffle-Dwelling Crayfish Density"},
                {"year": 2008, "title": "Imperiled crayfishes use hyporheic zone during seasonal drying of an intermittent stream"},
            ],
        },
        {
            "id": "145677056",
            "share": 15.6,
            "first_year": 1979,
            "last_year": 1997,
            "publications": [
                {"year": 1997, "title": "Cellular distribution of the rat D1B receptor in central nervous system using anti-receptor antisera."},
                {"year": 1997, "title": "Cellular distribution of the rat D4 dopamine receptor protein in the CNS using anti-receptor antisera."},
                {"year": 1997, "title": "Coexpression of striatal dopamine receptor subtypes and excitatory amino acid subunits"},
                {"year": 1996, "title": "Neurophysin expression is stimulated by dopamine D1 agonist in dispersed hypothalamic cultures."},
                {"year": 1995, "title": "D3 and D2 dopamine receptors: Visualization of cellular expression patterns in motor and limbic structures"},
                {"year": 1994, "title": "Dopamine receptor binding on identified striatonigral neurons."},
                {"year": 1994, "title": "Identification of tricyclic analogs related to ellagic acid as potent/selective tyrosine protein kinase inhibitors."},
                {"year": 1991, "title": "Novel, potent aldose reductase inhibitors: 3,4-dihydro-4-oxo-3-[[5-(trifluoromethyl)-2-benzothiazolyl] methyl]-1-phthalazineacetic acid (zopolrestat) and congeners."},
                {"year": 1988, "title": "Medicinal chemistry of aldose reductase inhibitors"},
                {"year": 1983, "title": "A totally synthetic route to lincosamine"},
                {"year": 1982, "title": "Mechanistic variations in the Lewis acid-catalyzed cyclocondensation of siloxydienes with aldehydes"},
                {"year": 1982, "title": "On the mechanism of the lewis acid catalyzed cyclocondensation of aldehydes with siloxydienes"},
                {"year": 1982, "title": "Stereochemical variations in the cyclocondensation of aldehydes with siloxydienes. An application to the erythronolide series"},
                {"year": 1982, "title": "Synthesis of (–)-steganone"},
                {"year": 1979, "title": "An improved route to steganone"},
            ],
        },
        {
            "id": "49159718",
            "share": 5.2,
            "first_year": 2002,
            "last_year": 2020,
            "publications": [
                {"year": 2020, "title": "Circulating endocannabinoid concentrations in grieving adults"},
                {"year": 2018, "title": "Do Patients With Advanced Cancer Have the Ability to Make Informed Decisions for Participation in Phase I Clinical Trials?"},
                {"year": 2018, "title": "Music-instruction intervention for treatment of post-traumatic stress disorder: a randomized pilot study"},
                {"year": 2005, "title": "Working memory and inhibitory control among manic and euthymic patients with bipolar disorder"},
                {"year": 2002, "title": "The Effects of Brief Interventions on Children's Playmate Preferences for a Child Sitting in a Wheelchair"},
            ],
        },
        {
            "id": "2291267842",
            "share": 4.2,
            "first_year": 2024,
            "last_year": 2025,
            "publications": [
                {"year": 2025, "title": "BioTIME 2.0: Expanding and Improving a Database of Biodiversity Time Series"},
                {"year": 2024, "title": "Aquatic invasive species exhibit contrasting seasonal detectability patterns based on environmental DNA: Implications for monitoring"},
                {"year": 2024, "title": "Comparing cost, effort, and performance of environmental DNA sampling and trapping for detecting an elusive freshwater turtle"},
                {"year": 2024, "title": "Environmental DNA storage and extraction method affects detectability for multiple aquatic invasive species"},
            ],
        },
        {
            "id": "2052551751",
            "share": 2.1,
            "first_year": 2010,
            "last_year": 2010,
            "publications": [
                {"year": 2010, "title": "Exploring differences in computerized neurocognitive concussion testing between African American and White athletes."},
                {"year": 2010, "title": "Investigating baseline neurocognitive performance between male and female athletes with a history of multiple concussion"},
            ],
        },
        {
            "id": "2247167812",
            "share": 2.1,
            "first_year": 1997,
            "last_year": 1999,
            "publications": [
                {"year": 1999, "title": "Brain magnetic resonance imaging of structural abnormalities in bipolar disorder."},
                {"year": 1997, "title": "Comparison of patients with early-, typical-, and late-onset affective psychosis."},
            ],
        },
        {
            "id": "34854453",
            "share": 2.1,
            "first_year": 1985,
            "last_year": 1985,
            "publications": [
                {"year": 1985, "title": "A totally synthetic route to lincosamine: some observations on the diastereofacial selectivity of electrophilic reactions on the double bonds of various 5-(1-alkenyl)arabinopyranosides"},
                {"year": 1985, "title": "On the scope, mechanism and stereochemistry of the Lewis acid catalyzed cyclocondensation of activated dienes with aldehydes: an application to the erythronolide problem"},
            ],
        },
        {
            "id": "108719833",
            "share": 1.0,
            "first_year": 2004,
            "last_year": 2004,
            "publications": [
                {"year": 2004, "title": "Age and growth of Scotia Sea icefish, Chaenocephalus aceratus, from the South Shetland Islands"},
            ],
        },
        {
            "id": "144161236",
            "share": 1.0,
            "first_year": 2011,
            "last_year": 2011,
            "publications": [
                {"year": 2011, "title": "Disaggregated End-Use Energy Sensing for the Smart Grid"},
            ],
        },
        {
            "id": "144752199",
            "share": 1.0,
            "first_year": 2020,
            "last_year": 2020,
            "publications": [
                {"year": 2020, "title": "Author Correction: SciPy 1.0: fundamental algorithms for scientific computing in Python"},
            ],
        },
        {
            "id": "1661097811",
            "share": 1.0,
            "first_year": 2020,
            "last_year": 2020,
            "publications": [
                {"year": 2020, "title": "Long-Term Aberrations To Cerebellar Endocannabinoids Induced By Early-Life Stress"},
            ],
        },
        {
            "id": "2052551719",
            "share": 1.0,
            "first_year": 2017,
            "last_year": 2017,
            "publications": [
                {"year": 2017, "title": "Rapid sealing of porcine renal blood vessels, ex vivo, using a high power, 1470-nm laser, and laparoscopic prototype"},
            ],
        },
        {
            "id": "2083209098",
            "share": 1.0,
            "first_year": 2018,
            "last_year": 2018,
            "publications": [
                {"year": 2018, "title": "Quantifying the contribution of zoos and aquariums to peer-reviewed scientific research"},
            ],
        },
        {
            "id": "50670820",
            "share": 1.0,
            "first_year": 2022,
            "last_year": 2022,
            "publications": [
                {"year": 2022, "title": "Ecological integrity is both real and valuable"},
            ],
        },
        {
            "id": "90825301",
            "share": 1.0,
            "first_year": 2004,
            "last_year": 2004,
            "publications": [
                {"year": 2004, "title": "A prospective open-label study to evaluate the effects of the oral contraceptive Harmonet (gestodene75/EE20) on body fat."},
            ],
        },
    ],
    "Boxuan Zhao": [
        {
            "id": "16269112",
            "share": 47.7,
            "first_year": 2010,
            "last_year": 2024,
            "publications": [
                {"year": 2024, "title": "Author Correction: Quantifying mammalian genomic DNA hydroxymethylcytosine content using solid-state nanopores"},
                {"year": 2023, "title": "Photochlorination of linear alkanes with 2-position selectivity using a metal-organic layer catalyst"},
                {"year": 2022, "title": "Progress in the study of antiplatelet and antithrombotic effects of salvia polyphenolic acid for injection"},
                {"year": 2022, "title": "Research progress on pharmacological action and mechanism of injection Yiqi Fumai lyophilized injection in treating cardiomyopathy"},
                {"year": 2020, "title": "DNA 5-Methylcytosine-Specific Amplification and Sequencing"},
                {"year": 2020, "title": "Publisher Correction: Recognition of RNA N6-methyladenosine by IGF2BP proteins enhances mRNA stability and translation"},
                {"year": 2020, "title": "RNA-protein interaction mapping via MS2 or Cas13-based APEX targeting"},
                {"year": 2020, "title": "RNA–protein interaction mapping via MS2- or Cas13-based APEX targeting"},
                {"year": 2019, "title": "Histone H3 trimethylation at lysine 36 guides m6A RNA modification co-transcriptionally"},
                {"year": 2018, "title": "Author Correction: Recognition of RNA N6-methyladenosine by IGF2BP proteins enhances mRNA stability and translation"},
                {"year": 2018, "title": "Long genes linked to autism spectrum disorders harbor broad enhancer-like chromatin domains"},
                {"year": 2018, "title": "Publisher Correction: Post-transcriptional gene regulation by mRNA modifications"},
                {"year": 2018, "title": "Recognition of RNA N6-methyladenosine by IGF2BP Proteins Enhances mRNA Stability and Translation"},
                {"year": 2017, "title": "\"Gamete On\" for m6A: YTHDF2 Exerts Essential Functions in Female Fertility."},
                {"year": 2017, "title": "Correction: N6-methyladenosine of HIV-1 RNA regulates viral infection and HIV-1 Gag protein expression"},
                {"year": 2017, "title": "Evolution of transcript modification by N6-methyladenosine in primates"},
                {"year": 2017, "title": "METTL14 Inhibits Hematopoietic Stem/Progenitor Differentiation and Promotes Leukemogenesis via mRNA m6A Modification"},
                {"year": 2017, "title": "Our views of dynamic N6-methyladenosine RNA methylation"},
                {"year": 2017, "title": "Post-transcriptional gene regulation by mRNA modifications"},
                {"year": 2017, "title": "The m6A Demethylase ALKBH5 Maintains Tumorigenicity of Glioblastoma Stem-Like Cells by Sustaining FOXM1 Expression and Cell Proliferation Program"},
                {"year": 2017, "title": "YTHDF3 facilitates translation and decay of N6-methyladenosine-modified RNA"},
                {"year": 2017, "title": "m6A-dependent maternal mRNA clearance facilitates zebrafish maternal-to-zygotic transition"},
                {"year": 2016, "title": "Dynamics of Human and Viral RNA Methylation during ZIKA Virus Infection"},
                {"year": 2016, "title": "N6-methyladenosine of HIV-1 RNA regulates viral infection and HIV-1 Gag protein expression"},
                {"year": 2016, "title": "Nucleic acid modifications in regulation of gene expression"},
                {"year": 2016, "title": "Quantifying mammalian genomic DNA hydroxymethylcytosine content using solid-state nanopores"},
                {"year": 2016, "title": "The N6-Adenine Methyltransferase METTL14 Plays an Oncogenic Role in Acute Myeloid Leukemia"},
                {"year": 2015, "title": "Base-resolution maps of 5-formylcytosine and 5-carboxylcytosine reveal genome-wide DNA demethylation dynamics"},
                {"year": 2015, "title": "Fate by RNA methylation: m6A steers stem cell pluripotency"},
                {"year": 2015, "title": "N6-methyladenosine Modulates Messenger RNA Translation Efficiency"},
                {"year": 2015, "title": "Pseudouridine in a new era of RNA modifications"},
                {"year": 2015, "title": "TET Family Proteins: Oxidation Activity, Interacting Molecules, and Functions in Diseases"},
                {"year": 2014, "title": "5mC oxidation by Tet2 modulates enhancer activity and timing of transcriptome reprogramming during differentiation"},
                {"year": 2014, "title": "Abstract 460: Base resolution epigenomic analysis reveals a role for Tet2 in modulating enhancer activity"},
                {"year": 2013, "title": "A highly sensitive and genetically encoded fluorescent reporter for ratiometric monitoring of quinones in living cells"},
                {"year": 2013, "title": "Probing subcellular organic hydroperoxide formation via a genetically encoded ratiometric and reversible fluorescent indicator."},
                {"year": 2013, "title": "The multiple antibiotic resistance regulator MarR is a copper sensor in Escherichia coli."},
                {"year": 2012, "title": "A selective fluorescent probe for carbon monoxide imaging in living cells."},
                {"year": 2010, "title": "A highly selective fluorescent probe for visualization of organic hydroperoxides in living cells."},
                {"year": None, "title": "N6-methyladenosine modification enables viral RNA to escape recognition by RNA sensor RIG-I"},
                {"year": None, "title": "Viral N6-methyladenosine upregulates replication and pathogenesis of human respiratory syncytial virus"},
            ],
        },
        {
            "id": "49217626",
            "share": 20.9,
            "first_year": 2011,
            "last_year": 2023,
            "publications": [
                {"year": 2023, "title": "Understanding the evolution of green ecology theory and future trends in urban development"},
                {"year": 2022, "title": "Improved Dual Attention for Anchor-Free Object Detection"},
                {"year": 2022, "title": "Multi-Scenario Simulation and Prediction of Regional Habitat Quality Based on a System Dynamic and Patch-Generating Land-Use Simulation Coupling Model—A Case Study of Jilin Province"},
                {"year": 2022, "title": "RLogist: Fast Observation Strategy on Whole-slide Images with Deep Reinforcement Learning"},
                {"year": 2022, "title": "The study of molecular ratio trend prediction of electrolytic tank based on deep learning"},
                {"year": 2021, "title": "A Comprehensive Review of Group Activity Recognition in Videos"},
                {"year": 2021, "title": "GLM-Net: Global and Local Motion Estimation via Task-Oriented Encoder-Decoder Structure"},
                {"year": 2021, "title": "XTuning: Expert Database Tuning System Based on Reinforcement Learning"},
                {"year": 2020, "title": "A multi-strategy integration Pareto based artificial colony algorithm for multi-objective flexible job shop scheduling problem with the earliness & tardiness criterion"},
                {"year": 2020, "title": "An Agent Based Simulation System for Open Source Software Development"},
                {"year": 2020, "title": "Fusing Motion Patterns and Key Visual Information for Semantic Event Recognition in Basketball Videos"},
                {"year": 2017, "title": "A security level classification method for power systems under N-1 contingency"},
                {"year": 2015, "title": "Two-generation Pareto ant colony algorithm for multi-objective job shop scheduling problem with alternative process plans and unrelated parallel machines"},
                {"year": 2015, "title": "Workload control-related Workload Route Decision"},
                {"year": 2014, "title": "Toward Safe Human Robot Collaboration by Using Multiple Kinects Based Real-Time Human Tracking"},
                {"year": 2013, "title": "Safe Human Robot Interaction by Using Exteroceptive Sensing Based Human Modeling"},
                {"year": 2012, "title": "Instruction Generation for Assembly Operations Performed by Humans"},
                {"year": 2011, "title": "Research on life of machine accuracy and precision reliability assessment concerning about a turn-milling combined machine tool"},
            ],
        },
        {
            "id": "2256773390",
            "share": 5.8,
            "first_year": 2023,
            "last_year": 2026,
            "publications": [
                {"year": 2026, "title": "Abstract PR004: Interactome-seq: A novel technology for mapping neuron-cancer synapses at single-cell resolution"},
                {"year": 2026, "title": "Connectome-seq: high-throughput mapping of neuronal connectivity at single-synapse resolution via barcode sequencing."},
                {"year": 2025, "title": "Connectome-seq: High-throughput Mapping of Neuronal Connectivity at Single-Synapse Resolution via Barcode Sequencing"},
                {"year": 2024, "title": "Unraveling the RNA Tapestry: A Symphony of Innovations in m6A Research Technology"},
                {"year": 2023, "title": "Opening New Avenues in Bioorganic Chemistry: Prof. Chuan He Receives the Tetrahedron Prize."},
            ],
        },
        {
            "id": "2350328070",
            "share": 5.8,
            "first_year": 2020,
            "last_year": 2025,
            "publications": [
                {"year": 2025, "title": "Coating and thermal polymerization of polyethylene oxide-based polymers on hollow fiber membranes for post-combustion CO2 capture"},
                {"year": 2025, "title": "Hydrogen-bonded network enabling ultrathin coating for post-combustion carbon capture"},
                {"year": 2023, "title": "Research on Optimizing the Configuration of Condenser in the Power Grid with Large Scale Renewable Energy"},
                {"year": 2021, "title": "The Hippo pathway: a renewed insight in the craniofacial diseases and hard tissue remodeling"},
                {"year": 2020, "title": "4D printing composite with electrically controlled local deformation"},
            ],
        },
        {
            "id": "2211176765",
            "share": 3.5,
            "first_year": 2023,
            "last_year": 2023,
            "publications": [
                {"year": 2023, "title": "Engineered allostery in light-regulated LOV-Turbo enables precise spatiotemporal control of proximity labeling in living cells"},
                {"year": 2023, "title": "Engineered allostery in light-regulated LOV-Turbo enables precise spatiotemporal control of proximity labeling in living cells"},
                {"year": 2023, "title": "Multicolor Patterning Inside a Metal‐Organic Framework"},
            ],
        },
        {
            "id": "2347749212",
            "share": 3.5,
            "first_year": 2025,
            "last_year": 2026,
            "publications": [
                {"year": 2026, "title": "Genetic and linguistic landscapes of Gansu-Qinghai populations"},
                {"year": 2025, "title": "Formation and Chemical Structure of Carbon-13 Tracer Lignin-Carbohydrate Complexes (LCCs) During Kraft Pulping"},
                {"year": 2025, "title": "Preparation of lignin-like polymers by dehydrogenation of lignin precursors and structure-activity relationships of the resulting polymers against live cancer HepG2 cells"},
            ],
        },
        {
            "id": "2143737719",
            "share": 2.3,
            "first_year": 2018,
            "last_year": 2022,
            "publications": [
                {"year": 2022, "title": "A Voltage Stability Research of Connecting Wind Farms to the Receive-side Grid Based on Torque Slip Curves"},
                {"year": 2018, "title": "Seeing on the surface of Eyeballs: Non-invasive visual substitution with the electro-tactile device on cornea"},
            ],
        },
        {
            "id": "2238727674",
            "share": 2.3,
            "first_year": 2023,
            "last_year": 2025,
            "publications": [
                {"year": 2025, "title": "Observation of metal-organic interphase in Cu-based electrochemical CO2-to-ethanol conversion"},
                {"year": 2023, "title": "Supported Fe Ions on Different Zr-Based Metal–Organic Frameworks for Alkane Oxidation"},
            ],
        },
        {
            "id": "2143736177",
            "share": 1.2,
            "first_year": 2022,
            "last_year": 2022,
            "publications": [
                {"year": 2022, "title": "A network pharmacology approach to explore the mechanism of action of Yiqi Fumai lyophilized injection in the treatment of novel coronavirus disease"},
            ],
        },
        {
            "id": "2143737250",
            "share": 1.2,
            "first_year": 2021,
            "last_year": 2021,
            "publications": [
                {"year": 2021, "title": "A facile method for constructing a superhydrophobic zinc coating on a steel surface with anti-corrosion and drag-reduction properties"},
            ],
        },
        {
            "id": "2143737404",
            "share": 1.2,
            "first_year": 1996,
            "last_year": 1996,
            "publications": [
                {"year": 1996, "title": "A strongly inwardly rectifying K+ channel that is sensitive to ATP"},
            ],
        },
        {
            "id": "2210072909",
            "share": 1.2,
            "first_year": 2025,
            "last_year": 2025,
            "publications": [
                {"year": 2025, "title": "NASH exacerbates inflammatory bone destruction and macrophage NLRP3 inflammasome activation in ligature-induced periodontitis."},
            ],
        },
        {
            "id": "2297128000",
            "share": 1.2,
            "first_year": 2025,
            "last_year": 2025,
            "publications": [
                {"year": 2025, "title": "Typological and ancient DNA evidences reveal the influence of Ming dynasty migration on the Shengjizui population in Bishan, Chongqing."},
            ],
        },
        {
            "id": "2308425688",
            "share": 1.2,
            "first_year": 1991,
            "last_year": 1991,
            "publications": [
                {"year": 1991, "title": "Cloning and expression of an Aplysia K+ channel and comparison with native Aplysia K+ currents"},
            ],
        },
        {
            "id": "2402801676",
            "share": 1.2,
            "first_year": 2024,
            "last_year": 2024,
            "publications": [
                {"year": 2024, "title": "Microwave-Assisted Synthesis of Solvatochromic Dye and Analysis of Solvent Polarity in Undergraduate Organic Chemistry Laboratory"},
            ],
        },
    ],
}
