S2_AUTHOR_CANDIDATES = {
    "Eric R. Larson": [
        ("39673101", 60.4, "From eDNA to citizen science: emerging tools for the early detection of invasive species"),
        ("145677056", 15.6, "Novel, potent aldose reductase inhibitors: 3,4-dihydro-4-oxo-3-[[5-(trifluoromethyl)-2-benzothiazolyl] methyl]-1-phthalazineacetic acid (zopolrestat) and congeners."),
        ("49159718", 5.2, "Working memory and inhibitory control among manic and euthymic patients with bipolar disorder"),
        ("2291267842", 4.2, "Comparing cost, effort, and performance of environmental DNA sampling and trapping for detecting an elusive freshwater turtle"),
        ("2052551751", 2.1, "Investigating baseline neurocognitive performance between male and female athletes with a history of multiple concussion"),
        ("2247167812", 2.1, "Brain magnetic resonance imaging of structural abnormalities in bipolar disorder."),
        ("34854453", 2.1, "On the scope, mechanism and stereochemistry of the Lewis acid catalyzed cyclocondensation of activated dienes with aldehydes: an application to the erythronolide problem"),
        ("108719833", 1.0, "Age and growth of Scotia Sea icefish, Chaenocephalus aceratus, from the South Shetland Islands"),
        ("144161236", 1.0, "Disaggregated End-Use Energy Sensing for the Smart Grid"),
        ("144752199", 1.0, "Author Correction: SciPy 1.0: fundamental algorithms for scientific computing in Python"),
        ("1661097811", 1.0, "Long-Term Aberrations To Cerebellar Endocannabinoids Induced By Early-Life Stress"),
        ("2052551719", 1.0, "Rapid sealing of porcine renal blood vessels, ex vivo, using a high power, 1470-nm laser, and laparoscopic prototype"),
        ("2083209098", 1.0, "Quantifying the contribution of zoos and aquariums to peer-reviewed scientific research"),
        ("50670820", 1.0, "Ecological integrity is both real and valuable"),
        ("90825301", 1.0, "A prospective open-label study to evaluate the effects of the oral contraceptive Harmonet (gestodene75/EE20) on body fat."),
    ],
    "Boxuan Zhao": [
        ("16269112", 47.7, "N6-methyladenosine Modulates Messenger RNA Translation Efficiency"),
        ("49217626", 20.9, "Toward Safe Human Robot Collaboration by Using Multiple Kinects Based Real-Time Human Tracking"),
        ("2256773390", 5.8, "Connectome-seq: high-throughput mapping of neuronal connectivity at single-synapse resolution via barcode sequencing."),
        ("2350328070", 5.8, "4D printing composite with electrically controlled local deformation"),
        ("2211176765", 3.5, "Engineered allostery in light-regulated LOV-Turbo enables precise spatiotemporal control of proximity labeling in living cells"),
        ("2347749212", 3.5, "Formation and Chemical Structure of Carbon-13 Tracer Lignin-Carbohydrate Complexes (LCCs) During Kraft Pulping"),
        ("2143737719", 2.3, "Seeing on the surface of Eyeballs: Non-invasive visual substitution with the electro-tactile device on cornea"),
        ("2238727674", 2.3, "Observation of metal-organic interphase in Cu-based electrochemical CO2-to-ethanol conversion"),
        ("2143736177", 1.2, "A network pharmacology approach to explore the mechanism of action of Yiqi Fumai lyophilized injection in the treatment of novel coronavirus disease"),
        ("2143737250", 1.2, "A facile method for constructing a superhydrophobic zinc coating on a steel surface with anti-corrosion and drag-reduction properties"),
        ("2143737404", 1.2, "A strongly inwardly rectifying K+ channel that is sensitive to ATP"),
        ("2210072909", 1.2, "NASH exacerbates inflammatory bone destruction and macrophage NLRP3 inflammasome activation in ligature-induced periodontitis."),
        ("2297128000", 1.2, "Typological and ancient DNA evidences reveal the influence of Ming dynasty migration on the Shengjizui population in Bishan, Chongqing."),
        ("2308425688", 1.2, "Cloning and expression of an Aplysia K+ channel and comparison with native Aplysia K+ currents"),
        ("2402801676", 1.2, "Microwave-Assisted Synthesis of Solvatochromic Dye and Analysis of Solvent Polarity in Undergraduate Organic Chemistry Laboratory"),
    ],
}
